version: '3.8'

services:

  node:
    labels:
      shipyard.route: '/'
    build:
      context: .
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
    volumes:
      - "./:/srv"